- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Role from collection
      include_role: geerlingguy.php_roles.php
    #- name: Include da-role
    #  include_role:
    #    name: geerlingguy.java
